Emuelec - Savestate - Fix
shantigilbert/emuelec-emulationstation pull request #92
Opened 2024-02-23 10:33 UTC by Langerz82

Emuelec - Savestate - Fix

Issue Listed Here:
https://github.com/EmuELEC/EmuELEC/issues/1313

Notes:
Fixes Issue.
For some reason when the config emulator/core are not set the empty variables over-write the arguments, so when loading from a save state, the emulator does not parse the defaults.
The fix was to check if the emular/core variables are not empty and if the are only then over-write the arguments.

Workaround:
I have not tested this but to get it working on the previous code, set the emulator and core in advanced game options and then it may use the config values and run savestates ok.

2024-02-23 16:29 UTC, shantigilbert commented
> For some reason when the config emulator/core are not set the empty variables over-write the arguments,

The thing is that at no time the core or emulator should be empty. I assume that is why there is no check in the original code. 
So how would this fix this issue? this just skips the argument but when it runs it will still not find the core and emu? since they are empty anyways.

2024-02-23 23:54 UTC, shantigilbert requested changes
please remove the changes from es-core/src/utils/Platform.cpp

2024-02-23 23:54 UTC, shantigilbert commented on es-core/src/utils/Platform.cpp
> +			return system("ee_shutdown.sh");
Let's focus on one change at a time please

2024-02-24 00:28 UTC, Langerz82 commented
Closed PR. Not needed. Will re-open and fix if need be.

2024-02-24 00:28 UTC, closed without merging